### ISSUE TITLE
Unable to find license

### ISSUE THREAD

**Issue by hyandell** [YuvrajGeek/json-server#2]
Hi Yuvraj,

I wasn't able to find a license for your project. Did you have a license you intended to be used?

**Comment by plusk-dev** [comment]
Hello Hyandell,
I currently do not have any license that is intended to be used. You can consider the source code to be free to use and redistribute.

**Comment by hyandell** [comment]
Thanks Yuvraj.

If it's okay, may I suggest the MIT license?  https://opensource.org/licenses/MIT

Typically, most free to use + redistribute cases are also fine with folk modifying them, and an open source licenses is used as a standard way to express that. Common free licensing _very_ roughly breaks down into:

1. Do what you want
2. Do what you want, but you need to mention you're using my software
3. Do what you want, but you need to give modifications of my files to your users
4. Do what you want, but you need to give the rest of the software you create to your users
5. Do some of what you want (usually no commercial use)

MIT is an example of the second one. It tells users the software is yours, that they can use/modify/distribute, as long as they include your license, and that you are not offering a warranty. To say the software is yours, you either put your name by the copyright statement, or a popular pattern now is to say "Copyright json-server Contributors", basically driving things back to GitHub to identify who did what. The MIT License is a very common/popular license - 44% of GitHub back in 2015 ( https://github.blog/2015-03-09-open-source-license-usage-on-github-com/ ) so this isn't me trying to get you to use something obscure :)

Let me know if that's okay and I'll happily send you a PR with a proposal on adding MIT; and apologies if you knew all this.

**Comment by plusk-dev** [comment]
I actually meant exactly what the second point says.
I'm completely okay with the license, looking forward to a PR.

May I know what are you using this code for?

**Comment by hyandell** [comment]
I went ahead and created a PR (#3). 

Use wise, I don't know :) For which I apologise as I know it's frustrating to not know the use cases. I work in the Open Source Program Office at Amazon and we have a PyPI ingestion process which flags whenever licensing isn't clear and pokes us to dig in; but we're not connected to the actual use. Because we've hit a lot of the core packages, it's typically because your package is showing somewhere in the dependency chain for another package, or because someone is interested in your package and poking around.

(For me personally, I'm intrigued by your orbital-patterns repository and plan to try it out in a few weeks with my space-excited high schooler, when the dayjob gives me a bit more time)

**Comment by plusk-dev** [comment]
Thanks for the PR.

It makes complete sense to flag packages when licensing isn't clear. I will definitely keep this in mind while working on my next package.

Enjoy playing around with the orbital-patterns repository, its really fun to spawn planets and watch them create awesome patterns. Good to see a space-excited high schooler appreciating a project made by a space-excited high schooler :)

Would you recommend to license the orbital-patterns repository too?
